#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/lancelot

PRODUCT_COPY_FILES += \
    vendor/xiaomi/lancelot/proprietary/odm/etc/galahad/android.hardware.secure_element@1.2-service-mediatek.rc:$(TARGET_COPY_OUT_ODM)/etc/galahad/android.hardware.secure_element@1.2-service-mediatek.rc \
    vendor/xiaomi/lancelot/proprietary/vendor/data/misc/pdc.txt:$(TARGET_COPY_OUT_VENDOR)/data/misc/pdc.txt \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param/AudioParamOptions.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param/HpImpedance_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param/Record_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamUnitDesc.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param/SmartPa_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param/SoundEnhancement_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param/VoIPv2DMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param_global/AudioParamOptions.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/AudioParamOptions.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param_global/HpImpedance_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/HpImpedance_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param_global/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/PlaybackACF_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param_global/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/PlaybackDRC_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param_global/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/PlaybackVolAna_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param_global/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/PlaybackVolDigi_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param_global/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/RecordFIR_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param_global/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/RecordVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param_global/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/RecordVol_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param_global/Record_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/Record_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param_global/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/Record_ParamUnitDesc.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param_global/SmartPa_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/SmartPa_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param_global/SoundEnhancement_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/SoundEnhancement_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param_global/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/SpeechDMNR_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param_global/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/SpeechGeneral_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param_global/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/SpeechVol_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param_global/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/Speech_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param_global/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoIPVol_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param_global/VoIPv2DMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoIPv2DMNR_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/audio_param_global/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_global/VoIPv2_AudioParam.xml \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/camera/golden_ov13b10_i_ov2180_i.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/golden_ov13b10_i_ov2180_i.bin \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/camera/golden_rear_dc_cal_wd.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/golden_rear_dc_cal_wd.bin \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/camera/golden_s5k3l6_ii_ov2180_ii.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/golden_s5k3l6_ii_ov2180_ii.bin \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/camera/model/bokeh_model/cache_data:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/bokeh_model/cache_data \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/camera/model/bokeh_model/model_mdl_cache:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/bokeh_model/model_mdl_cache \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/camera/model/bokeh_model/segment_model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/bokeh_model/segment_model \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/camera/model/rt_model/score/segment_model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/rt_model/score/segment_model \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/init/gsm0710muxd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/gsm0710muxd.rc \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/init/init.cccimdinit.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccimdinit.rc \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/init/init.cccirpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccirpcd.rc \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/init/init.md_apps.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.md_apps.rc \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/init/init.udc_lib.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.udc_lib.rc \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/init/init.volte_imcb.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_imcb.rc \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/init/init.volte_imsm_93.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_imsm_93.rc \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/init/init.volte_md_status.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_md_status.rc \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/init/init.volte_stack.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_stack.rc \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/init/init.volte_ua.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_ua.rc \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/init/microtrust.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/microtrust.rc \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/init/mtkrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtkrild.rc \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/init/muxreport.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/muxreport.rc \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/libnfc-nxp-pnscr.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp-pnscr.conf \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/libnfc-nxp_RF.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp_RF.conf \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/sn100u_nfcon.pnscr:$(TARGET_COPY_OUT_VENDOR)/etc/sn100u_nfcon.pnscr \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/sn100u_pnx_chr.pnscr:$(TARGET_COPY_OUT_VENDOR)/etc/sn100u_pnx_chr.pnscr \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/sn100u_pnx_cui.pnscr:$(TARGET_COPY_OUT_VENDOR)/etc/sn100u_pnx_cui.pnscr \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/sn100u_pnx_ese_3.pnscr:$(TARGET_COPY_OUT_VENDOR)/etc/sn100u_pnx_ese_3.pnscr \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/sn100u_pnx_ndi.pnscr:$(TARGET_COPY_OUT_VENDOR)/etc/sn100u_pnx_ndi.pnscr \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/sn100u_pnx_pcv.pnscr:$(TARGET_COPY_OUT_VENDOR)/etc/sn100u_pnx_pcv.pnscr \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/sn100u_pnx_sst.pnscr:$(TARGET_COPY_OUT_VENDOR)/etc/sn100u_pnx_sst.pnscr \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/thermal-camera.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-camera.conf \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/thermal-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-normal.conf \
    vendor/xiaomi/lancelot/proprietary/vendor/etc/thermal-tgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-tgame.conf \
    vendor/xiaomi/lancelot/proprietary/vendor/firmware/aw87519_drcv.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw87519_drcv.bin \
    vendor/xiaomi/lancelot/proprietary/vendor/firmware/aw87519_hvload.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw87519_hvload.bin \
    vendor/xiaomi/lancelot/proprietary/vendor/firmware/aw87519_kspk.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw87519_kspk.bin \
    vendor/xiaomi/lancelot/proprietary/vendor/firmware/awinic_params.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/awinic_params.bin \
    vendor/xiaomi/lancelot/proprietary/vendor/firmware/fm_cust_j19.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/fm_cust_j19.cfg \
    vendor/xiaomi/lancelot/proprietary/vendor/firmware/focaltech_mp_fw_huaxing.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech_mp_fw_huaxing.ini \
    vendor/xiaomi/lancelot/proprietary/vendor/firmware/focaltech_ts_fw_huaxing.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech_ts_fw_huaxing.bin \
    vendor/xiaomi/lancelot/proprietary/vendor/firmware/nvt_dj_72d_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvt_dj_72d_fw.bin \
    vendor/xiaomi/lancelot/proprietary/vendor/firmware/nvt_dj_72d_mp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvt_dj_72d_mp.bin \
    vendor/xiaomi/lancelot/proprietary/vendor/firmware/nvt_dj_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvt_dj_fw.bin \
    vendor/xiaomi/lancelot/proprietary/vendor/firmware/nvt_dj_mp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvt_dj_mp.bin \
    vendor/xiaomi/lancelot/proprietary/vendor/firmware/nvt_tm_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvt_tm_fw.bin \
    vendor/xiaomi/lancelot/proprietary/vendor/firmware/nvt_tm_mp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvt_tm_mp.bin \
    vendor/xiaomi/lancelot/proprietary/vendor/thh/ta/020b0000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/020b0000000000000000000000000000.ta \
    vendor/xiaomi/lancelot/proprietary/vendor/thh/ta/020f0000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/020f0000000000000000000000000000.ta \
    vendor/xiaomi/lancelot/proprietary/vendor/thh/ta/05120000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/05120000000000000000000000000000.ta \
    vendor/xiaomi/lancelot/proprietary/vendor/thh/ta/06090000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/06090000000000000000000000000000.ta \
    vendor/xiaomi/lancelot/proprietary/vendor/thh/ta/07060000000000000000000000007169.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/07060000000000000000000000007169.ta \
    vendor/xiaomi/lancelot/proprietary/vendor/thh/ta/08020000000000000000000000007169.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08020000000000000000000000007169.ta \
    vendor/xiaomi/lancelot/proprietary/vendor/thh/ta/08030000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08030000000000000000000000000000.ta \
    vendor/xiaomi/lancelot/proprietary/vendor/thh/ta/08070000000000000000000000008270.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08070000000000000000000000008270.ta \
    vendor/xiaomi/lancelot/proprietary/vendor/thh/ta/08110000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08110000000000000000000000000000.ta \
    vendor/xiaomi/lancelot/proprietary/vendor/thh/ta/09010000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/09010000000000000000000000000000.ta \
    vendor/xiaomi/lancelot/proprietary/vendor/thh/ta/09030000000000000000000000008270.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/09030000000000000000000000008270.ta \
    vendor/xiaomi/lancelot/proprietary/vendor/thh/ta/40188311faf343488db888ad39496f9a.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/40188311faf343488db888ad39496f9a.ta \
    vendor/xiaomi/lancelot/proprietary/vendor/thh/ta/5020170115e016302017012521300000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/5020170115e016302017012521300000.ta \
    vendor/xiaomi/lancelot/proprietary/vendor/thh/ta/9073f03a9618383bb1856eb3f990babd.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/9073f03a9618383bb1856eb3f990babd.ta \
    vendor/xiaomi/lancelot/proprietary/vendor/thh/ta/98fb95bcb4bf42d26473eae48690d7ea.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/98fb95bcb4bf42d26473eae48690d7ea.ta \
    vendor/xiaomi/lancelot/proprietary/vendor/thh/ta/e97c270ea5c44c58bcd3384a2fa2539e.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/e97c270ea5c44c58bcd3384a2fa2539e.ta

PRODUCT_PACKAGES += \
    libcarrierconfig \
    libcustom_nvram \
    libipsec_ims_shr \
    libmsbc_mtk \
    libmtkcutils \
    libmtkproperty \
    libmtkrillog \
    libverno \
    audio.primary.mt6768 \
    librt_extamp_intf \
    libvolte_core_shr \
    libvolte_xdmc_shr \
    gc5035_ofilm_mipi_raw_IdxMgr \
    gc5035_ofilm_mipi_raw_india_IdxMgr \
    gc5035_ofilm_mipi_raw_india_tuning \
    gc5035_ofilm_mipi_raw_tuning \
    gc5035_qtech_mipi_raw_IdxMgr \
    gc5035_qtech_mipi_raw_india_IdxMgr \
    gc5035_qtech_mipi_raw_india_tuning \
    gc5035_qtech_mipi_raw_tuning \
    hq_asd \
    android.hardware.camera.provider@2.6-impl-mediatek \
    sensors.mt6768 \
    vendor.mediatek.hardware.camera.isphal@1.0-impl \
    lib3a.ae.core \
    lib3a.ae \
    lib3a.af.core \
    lib3a.af \
    lib3a.awb.core \
    lib3a.awb \
    lib3a.ccudrv \
    lib3a.ccuif \
    lib3a.flash \
    lib3a.gma \
    lib3a.lce \
    lib3a.log \
    lib3a.n3d3a \
    libSQLiteModule_VER_ALL \
    libSonyIMX230PdafLibrary \
    libSonyIMX230PdafLibraryWrapper \
    libSonyIMX338PdafLibrary \
    libSonyIMX338PdafLibraryWrapper \
    libSonyIMX386PdafLibrary \
    libSonyIMX386PdafLibraryWrapper \
    libSonyIMX519PdafLibrary \
    libSonyIMX519PdafLibraryWrapper \
    lib_bsscore \
    lib_misd \
    libaal_cust \
    libabfadp \
    libakm \
    libalLDC \
    libalhLDC \
    libaltek_ldc_cp \
    libaltek_ldc_preview \
    libarcsoft_beautyshot \
    libarcsoft_facebeauty \
    libarcsoft_hdr \
    libarcsoft_high_dynamic_range \
    libarcsoft_low_light_hdr \
    libarcsoft_sn_J19 \
    libarcsoft_supernight \
    libc++_shared \
    libc++_shared_vf \
    libcam.chdr \
    libcam.feature_utils \
    libcam.hal3a.cctsvr \
    libcam.hal3a.log \
    libcam.hal3a.v3.dng \
    libcam.hal3a.v3.lsctbl \
    libcam.hal3a.v3.nvram \
    libcam.hal3a.v3 \
    libcam.halisp \
    libcam.halsensor.hwintegration \
    libcam.halsensor \
    libcam.iopipe \
    libcam.lcs \
    libcam.pdtblgen \
    libcam.utils.sensorprovider \
    libcam.vhdr \
    libcamalgo.3dnr \
    libcamalgo.abf \
    libcamalgo.dngop \
    libcamalgo.eis \
    libcamalgo.fdft \
    libcamalgo.flicker \
    libcamalgo.fsc \
    libcamalgo.gyro \
    libcamalgo.ispfeature \
    libcamalgo.lmv \
    libcamalgo.lsc \
    libcamalgo.mfnr \
    libcamalgo.nr \
    libcamalgo.platform \
    libcamalgo.platform2 \
    libcamalgo.utility \
    libcamalgo.warp \
    libcamdrv_imem \
    libcamdrv_isp \
    libcamdrv_tuning_mgr \
    libcamdrv_twin \
    libcamera_scene \
    libcameracustom.plugin \
    libcameracustom \
    libcares_naptr \
    libccci_util \
    libcurl_xcap_md \
    libdecrypt \
    libeffecthal.base \
    libfeature.face \
    libfeature.stereo.provider \
    libfeature_3dnr \
    libfeature_fsc \
    libfeature_lmv \
    libfeature_rss \
    libfeatureiodrv_mem \
    libfft_vendor \
    libft2vendor \
    libhq_videofilter \
    libimageio \
    libimageio_plat_drv \
    libimageio_plat_pipe \
    liblpcnr \
    libmfllcore \
    libmiStereoFactoryRemapLib \
    libmi_bokehcap \
    libmi_bokehpre \
    libmi_watermark \
    libmialgo_basic \
    libmialgo_sd \
    libmialgo_utils \
    libmibokeh_mt6768 \
    libmipc \
    libmpbase \
    libmsnr \
    libmtk-fusion-ril-prop-vsim \
    libmtk-ril \
    libmtkares \
    libmtkcam.eventcallback \
    libmtkcam.featurepipe.capture \
    libmtkcam.featurepipe.streaming \
    libmtkcam.featurepipe.vsdof_util \
    libmtkcam.logicalmodule \
    libmtkcam_3rdparty.core \
    libmtkcam_3rdparty.customer \
    libmtkcam_3rdparty.mtk \
    libmtkcam_3rdparty \
    libmtkcam_calibration_convertor \
    libmtkcam_calibration_provider \
    libmtkcam_debugutils \
    libmtkcam_device3_app \
    libmtkcam_device3_hal \
    libmtkcam_device3_hidl \
    libmtkcam_device3_hidlutils \
    libmtkcam_device3_utils \
    libmtkcam_devicesessionpolicy \
    libmtkcam_diputils \
    libmtkcam_exif \
    libmtkcam_fdvt \
    libmtkcam_featurepolicy \
    libmtkcam_featureutils \
    libmtkcam_fwkutils \
    libmtkcam_grallocutils \
    libmtkcam_hwnode \
    libmtkcam_hwutils \
    libmtkcam_imem \
    libmtkcam_imgbuf \
    libmtkcam_metadata \
    libmtkcam_metastore \
    libmtkcam_modulefactory_aaa \
    libmtkcam_modulefactory_custom \
    libmtkcam_modulefactory_drv \
    libmtkcam_modulefactory_utils \
    libmtkcam_modulehelper \
    libmtkcam_pipeline \
    libmtkcam_pipeline_fbm \
    libmtkcam_pipelinemodel \
    libmtkcam_pipelinemodel_adapter \
    libmtkcam_pipelinemodel_capture \
    libmtkcam_pipelinemodel_isp \
    libmtkcam_pipelinemodel_session \
    libmtkcam_pipelinemodel_utils \
    libmtkcam_pipelinemodel_zsl \
    libmtkcam_pipelinepolicy-aov \
    libmtkcam_pipelinepolicy-security \
    libmtkcam_pipelinepolicy-smvr \
    libmtkcam_pipelinepolicy \
    libmtkcam_pipelinepolicy_factory \
    libmtkcam_prerelease \
    libmtkcam_rsc \
    libmtkcam_scenariorecorder \
    libmtkcam_stdutils \
    libmtkcam_streamutils \
    libmtkcam_synchelper \
    libmtkcam_sysutils \
    libmtkcam_tuning_utils \
    libmtkcam_ulog \
    libmtkcam_vsync_util \
    libmtkconfig \
    libmtkconfigutils \
    libmtkhardware_legacy \
    libmtkisp_metadata \
    libmtkmipc-ril \
    libmtknetcap \
    libmtknetutils \
    libmtkrilutils \
    libmtksysutils \
    libmtktinyxml \
    libmtkutils \
    libratconfig \
    libremosaic_wrapper \
    libremosaiclib \
    librilfusion \
    librpc \
    libsensor_custom \
    libsimlock \
    libsimmelock \
    libstereoinfoaccessor_vsdof \
    libsysenv \
    libtrm \
    libutinterface_custom_md \
    libutinterface_md \
    libvia-ril \
    libviagpsrpc \
    libvideofilter_only \
    libvidhance \
    libwa_ancbase \
    libwa_depth \
    libwa_refocus \
    libwa_rtdof \
    libwo \
    libwpfa \
    libmtkcam_streaminfo_plugin-p1stt \
    ov13b10_ofilm_mipi_raw_IdxMgr \
    ov13b10_ofilm_mipi_raw_india_IdxMgr \
    ov13b10_ofilm_mipi_raw_india_tuning \
    ov13b10_ofilm_mipi_raw_tuning \
    ov13b10_qtech_mipi_raw_IdxMgr \
    ov13b10_qtech_mipi_raw_india_IdxMgr \
    ov13b10_qtech_mipi_raw_india_tuning \
    ov13b10_qtech_mipi_raw_tuning \
    ov2180_ofilm_mipi_raw_IdxMgr \
    ov2180_ofilm_mipi_raw_india_IdxMgr \
    ov2180_ofilm_mipi_raw_india_tuning \
    ov2180_ofilm_mipi_raw_tuning \
    ov2180_qtech_mipi_raw_IdxMgr \
    ov2180_qtech_mipi_raw_india_IdxMgr \
    ov2180_qtech_mipi_raw_india_tuning \
    ov2180_qtech_mipi_raw_tuning \
    ov8856_qtech_front_mipi_raw_IdxMgr \
    ov8856_qtech_front_mipi_raw_india_IdxMgr \
    ov8856_qtech_front_mipi_raw_india_tuning \
    ov8856_qtech_front_mipi_raw_tuning \
    ov8856_qtech_ultra_mipi_raw_IdxMgr \
    ov8856_qtech_ultra_mipi_raw_india_IdxMgr \
    ov8856_qtech_ultra_mipi_raw_india_tuning \
    ov8856_qtech_ultra_mipi_raw_tuning \
    s5k3l6_qtech_mipi_raw_IdxMgr \
    s5k3l6_qtech_mipi_raw_india_IdxMgr \
    s5k3l6_qtech_mipi_raw_india_tuning \
    s5k3l6_qtech_mipi_raw_tuning \
    s5k4h7yx_ofilm_front_mipi_raw_IdxMgr \
    s5k4h7yx_ofilm_front_mipi_raw_india_IdxMgr \
    s5k4h7yx_ofilm_front_mipi_raw_india_tuning \
    s5k4h7yx_ofilm_front_mipi_raw_tuning \
    s5k4h7yx_ofilm_ultra_mipi_raw_IdxMgr \
    s5k4h7yx_ofilm_ultra_mipi_raw_india_IdxMgr \
    s5k4h7yx_ofilm_ultra_mipi_raw_india_tuning \
    s5k4h7yx_ofilm_ultra_mipi_raw_tuning \
    vendor.mediatek.hardware.camera.bgservice@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.1 \
    vendor.mediatek.hardware.mdmonitor@1.0 \
    vendor.mediatek.hardware.mtkradioex@2.0 \
    vendor.mediatek.hardware.mtkradioex@3.0 \
    LDC_packdata_xiaomi_J19_Ofilm_3280x2464.dat \
    LDC_packdata_xiaomi_J19_QTech_3264x2448.dat \
    ccci_mdinit \
    ccci_rpcd \
    charon \
    epdg_wod \
    fuelgauged_nvram \
    gsm0710muxd \
    android.hardware.secure_element@1.2-service-mediatek \
    camerahalserver \
    mtkfusionrild \
    libccu_ov13b10_ofilm_mipi_raw.dm \
    libccu_ov13b10_ofilm_mipi_raw.pm \
    libccu_ov13b10_qtech_mipi_raw.dm \
    libccu_ov13b10_qtech_mipi_raw.pm \
    libccu_ov2180_ofilm_mipi_raw.dm \
    libccu_ov2180_ofilm_mipi_raw.pm \
    libccu_ov2180_qtech_mipi_raw.dm \
    libccu_ov2180_qtech_mipi_raw.pm \
    libccu_ov8856_qtech_front_mipi_raw.dm \
    libccu_ov8856_qtech_front_mipi_raw.pm \
    libccu_ov8856_qtech_ultra_mipi_raw.dm \
    libccu_ov8856_qtech_ultra_mipi_raw.pm \
    libccu_s5k3l6_qtech_mipi_raw.dm \
    libccu_s5k3l6_qtech_mipi_raw.pm \
    libccu_s5k4h7yx_ofilm_front_mipi_raw.dm \
    libccu_s5k4h7yx_ofilm_front_mipi_raw.pm \
    libccu_s5k4h7yx_ofilm_ultra_mipi_raw.dm \
    libccu_s5k4h7yx_ofilm_ultra_mipi_raw.pm \
    muxreport \
    nusensors \
    nvram_daemon \
    pnscr \
    starter \
    stroke \
    teei_daemon \
    volte_imcb \
    volte_imsm_93 \
    volte_md_status \
    volte_stack \
    volte_ua
